using System.Data;
using System.Text.Json;
using Xunit.Abstractions;

namespace SqlInterpol.Testing.Xunit;

/// <summary>
/// Represents a data-driven test case for SQL generation, encapsulating both the expected outcomes 
/// (SQL, parameters, or exceptions) and tracking the actual results generated during execution.
/// </summary>
public sealed class SqlTestCase : IXunitSerializable
{
    /// <summary>
    /// Holds the active live database connection for E2E specification execution.
    /// When populated by an E2E test fixture, generated queries are executed against the real database engine.
    /// </summary>
    public static AsyncLocal<IDbConnection?> CurrentConnection { get; } = new();

    /// <summary>
    /// Gets a helper instance used to assert that the actual execution results match the expected state.
    /// </summary>
    public SqlTestCaseAssert Assert => new(this);
    
    /// <summary>
    /// Gets the list of actual SQL strings generated during the test execution.
    /// </summary>
    public List<string> ActualSql { get; } = [];

    /// <summary>
    /// Gets the list of actual parameter arrays generated during the test execution.
    /// </summary>
    public List<object?[]> ActualParametersList { get; } = [];

    /// <summary>
    /// Gets the list of exceptions thrown during the test execution.
    /// </summary>
    public List<Exception> ActualExceptions { get; } = [];
    
    /// <summary>
    /// Gets the type of the first exception thrown during execution, if any.
    /// </summary>
    public Type? ActualExceptionType => ActualExceptions.FirstOrDefault()?.GetType();

    /// <summary>
    /// Gets the exact column names returned by the database during E2E execution.
    /// </summary>
    public string[]? ActualColumns { get; private set; }

    /// <summary>
    /// Gets the number of rows returned by a query or affected by a mutation during E2E execution.
    /// </summary>
    public int? ActualRowCount { get; private set; }

    /// <summary>
    /// Gets the JSON-serialized representation of the actual rows returned during E2E execution.
    /// </summary>
    public string? ActualDataJson { get; private set; }

    /// <summary>
    /// Gets the array of expected SQL strings that should be generated by the operation.
    /// </summary>
    public string[]? ExpectedSql { get; private set; }

    /// <summary>
    /// Gets the expected parameters that should accompany the generated SQL.
    /// </summary>
    public object?[] ExpectedParameters { get; private set; } = [];

    /// <summary>
    /// Gets the expected database state and structure for E2E test validation.
    /// </summary>
    public SqlTestDbData? ExpectedData { get; private set; }

    /// <summary>
    /// Gets the type of exception expected to be thrown, typically for unsupported features or invalid syntax.
    /// </summary>
    public Type? ExpectedExceptionType { get; private set; }

    /// <summary>
    /// Gets the exact exception message expected to be thrown, if applicable.
    /// </summary>
    public string? ExpectedExceptionMessage { get; private set; }

    /// <summary>
    /// Gets the optional identifier used to label this test case in the xUnit Test Explorer.
    /// </summary>
    public string? Id { get; private set; }

    /// <summary>
    /// Initializes a new instance of the <see cref="SqlTestCase"/> class. 
    /// Required for xUnit cross-AppDomain deserialization.
    /// </summary>
    public SqlTestCase() { }

    /// <summary>
    /// Initializes a new test case that expects a successful SQL string generation, and optionally verifies E2E database state.
    /// </summary>
    /// <param name="expectedSql">The expected SQL strings.</param>
    /// <param name="expectedParameters">The expected SQL parameters.</param>
    /// <param name="expectedData">The expected database state and structural assertions.</param>
    /// <param name="id">An optional identifier for the test case.</param>
    public SqlTestCase(string[] expectedSql, object?[]? expectedParameters = null, SqlTestDbData? expectedData = null, string? id = null)
    {
        ExpectedSql = expectedSql ?? throw new ArgumentNullException(nameof(expectedSql));
        if (expectedSql.Length == 0) throw new ArgumentException("ExpectedSql cannot be empty.", nameof(expectedSql));
        
        ExpectedParameters = expectedParameters ?? [];
        ExpectedData = expectedData;
        Id = id;
    }

    /// <summary>
    /// Initializes a new test case that expects an exception to be thrown.
    /// </summary>
    /// <param name="expectedExceptionType">The type of the expected exception.</param>
    /// <param name="expectedExceptionMessage">The expected exception message.</param>
    /// <param name="id">An optional identifier for the test case.</param>
    public SqlTestCase(Type expectedExceptionType, string? expectedExceptionMessage = null, string? id = null)
    {
        ExpectedExceptionType = expectedExceptionType ?? throw new ArgumentNullException(nameof(expectedExceptionType));
        ExpectedExceptionMessage = expectedExceptionMessage;
        Id = id;
    }

    /// <summary>
    /// Executes the SQL generation logic, captures the output state, and automatically 
    /// runs the query against a live database if an E2E connection is active.
    /// </summary>
    /// <param name="act">The function representing the SQL builder execution.</param>
    public void Act(Func<SqlQueryResult> act)
    {
        try
        {
            var result = act();
            ActualSql.Add(result.Sql);
            ActualParametersList.Add(result.Parameters.Select(p => p.Value).ToArray());

            // E2E Database Execution Bridge
            if (CurrentConnection.Value is { } connection)
            {
                using var command = connection.CreateCommand();
                command.CommandText = result.Sql;

                // Use raw ADO.NET mapping to avoid forcing a Dapper dependency on the testing library
                foreach (var p in result.Parameters)
                {
                    var param = command.CreateParameter();
                    param.ParameterName = p.Key;
                    param.Value = p.Value ?? DBNull.Value;
                    command.Parameters.Add(param);
                }

                // If a VerifySql is provided, execute the main query as a mutation first
                if (ExpectedData?.VerifySql != null)
                {
                    ActualRowCount = command.ExecuteNonQuery();
                    
                    command.CommandText = ExpectedData.VerifySql;
                    command.Parameters.Clear(); // Verify query is assumed parameterless
                }

                // ExecuteReader to capture schema and data
                using var reader = command.ExecuteReader();
                
                ActualColumns = Enumerable.Range(0, reader.FieldCount)
                                          .Select(reader.GetName)
                                          .ToArray();
                
                var actualRows = new List<Dictionary<string, object?>>();
                while (reader.Read())
                {
                    var row = new Dictionary<string, object?>();
                    for (int i = 0; i < reader.FieldCount; i++)
                    {
                        var val = reader.GetValue(i);
                        row[ActualColumns[i]] = val == DBNull.Value ? null : val;
                    }
                    actualRows.Add(row);
                }

                // If no VerifySql was executed, the row count is the number of fetched rows
                if (ExpectedData?.VerifySql == null)
                {
                    ActualRowCount = actualRows.Count;
                }
                
                // Serialize actual results if we have data expectations to compare against
                if (ExpectedData?.DataJson != null)
                {
                    ActualDataJson = JsonSerializer.Serialize(actualRows);
                }
            }
        }
        catch (Exception ex)
        {
            ActualExceptions.Add(ex);
        }
    }

    /// <summary>
    /// Serializes the test case context for xUnit cross-AppDomain execution.
    /// </summary>
    /// <param name="info">The xUnit serialization info.</param>
    public void Serialize(IXunitSerializationInfo info)
    {
        info.AddValue(nameof(ExpectedSql), ExpectedSql);
        info.AddValue(nameof(ExpectedExceptionType), ExpectedExceptionType?.AssemblyQualifiedName);
        info.AddValue(nameof(ExpectedExceptionMessage), ExpectedExceptionMessage);
        info.AddValue(nameof(ExpectedParameters), ExpectedParameters);
        info.AddValue(nameof(Id), Id);

        // Serialize ExpectedDb flattened properties
        info.AddValue("Db_Columns", ExpectedData?.Columns);
        info.AddValue("Db_RowCount", ExpectedData?.RowCount);
        info.AddValue("Db_VerifySql", ExpectedData?.VerifySql);
        info.AddValue("Db_DataJson", ExpectedData?.DataJson);
    }

    /// <summary>
    /// Deserializes the test case context from xUnit cross-AppDomain execution.
    /// </summary>
    /// <param name="info">The xUnit serialization info.</param>
    public void Deserialize(IXunitSerializationInfo info)
    {
        ExpectedSql = info.GetValue<string[]>(nameof(ExpectedSql));
        ExpectedParameters = info.GetValue<object?[]>(nameof(ExpectedParameters)) ?? [];

        var expectedExceptionTypeName = info.GetValue<string>(nameof(ExpectedExceptionType));
        if (!string.IsNullOrEmpty(expectedExceptionTypeName))
        {
            ExpectedExceptionType = Type.GetType(expectedExceptionTypeName);
        }

        ExpectedExceptionMessage = info.GetValue<string>(nameof(ExpectedExceptionMessage));
        Id = info.GetValue<string>(nameof(Id));

        // Deserialize ExpectedDb flattened properties
        var dbColumns = info.GetValue<string[]?>("Db_Columns");
        var dbRowCount = info.GetValue<int?>("Db_RowCount");
        var dbVerifySql = info.GetValue<string?>("Db_VerifySql");
        var dbDataJson = info.GetValue<string?>("Db_DataJson");

        if (dbColumns != null || dbRowCount != null || dbVerifySql != null || dbDataJson != null)
        {
            ExpectedData = new SqlTestDbData 
            { 
                Columns = dbColumns, 
                RowCount = dbRowCount, 
                VerifySql = dbVerifySql, 
                DataJson = dbDataJson 
            };
        }
    }

    /// <summary>
    /// Returns the string representation of the test case, typically used for xUnit display names.
    /// </summary>
    /// <returns>The identifier or a default name.</returns>
    public override string ToString()
    {
        return string.IsNullOrWhiteSpace(Id) ? "TestCase" : Id;
    }
}