using System.Data;
using Xunit.Abstractions;

namespace SqlInterpol.Testing.Xunit;

/// <summary>
/// Represents a data-driven test case for SQL generation, encapsulating both the expected outcomes 
/// (SQL, parameters, or exceptions) and tracking the actual results generated during execution.
/// </summary>
public sealed class SqlTestCase : IXunitSerializable
{
    /// <summary>
    /// Holds the active live database connection for E2E specification execution.
    /// When populated by an E2E test fixture, generated queries are executed against the real database engine.
    /// </summary>
    public static AsyncLocal<IDbConnection?> CurrentConnection { get; } = new();

    /// <summary>
    /// Gets a helper instance used to assert that the actual execution results match the expected state.
    /// </summary>
    public SqlTestCaseAssert Assert => new(this);
    
    /// <summary>
    /// Gets the list of actual SQL strings generated during the test execution.
    /// </summary>
    public List<string> ActualSql { get; } = [];

    /// <summary>
    /// Gets the list of actual parameter arrays generated during the test execution.
    /// </summary>
    public List<object?[]> ActualParametersList { get; } = [];

    /// <summary>
    /// Gets the list of exceptions thrown during the test execution.
    /// </summary>
    public List<Exception> ActualExceptions { get; } = [];
    
    /// <summary>
    /// Gets the type of the first exception thrown during execution, if any.
    /// </summary>
    public Type? ActualExceptionType => ActualExceptions.FirstOrDefault()?.GetType();

    /// <summary>
    /// Gets the array of expected SQL strings that should be generated by the operation.
    /// </summary>
    public string[]? ExpectedSql { get; private set; }

    /// <summary>
    /// Gets the expected parameters that should accompany the generated SQL.
    /// </summary>
    public object?[] ExpectedParameters { get; private set; } = [];

    /// <summary>
    /// Gets the type of exception expected to be thrown, typically for unsupported features or invalid syntax.
    /// </summary>
    public Type? ExpectedExceptionType { get; private set; }

    /// <summary>
    /// Gets the exact exception message expected to be thrown, if applicable.
    /// </summary>
    public string? ExpectedExceptionMessage { get; private set; }

    /// <summary>
    /// Gets the optional identifier used to label this test case in the xUnit Test Explorer.
    /// </summary>
    public string? Id { get; private set; }

    /// <summary>
    /// Initializes a new instance of the <see cref="SqlTestCase"/> class. 
    /// Required for xUnit cross-AppDomain deserialization.
    /// </summary>
    public SqlTestCase() { }

    /// <summary>
    /// Initializes a new test case that expects a successful SQL string generation.
    /// </summary>
    public SqlTestCase(string[] expectedSql, object?[]? expectedParameters = null, string? id = null)
    {
        ExpectedSql = expectedSql ?? throw new ArgumentNullException(nameof(expectedSql));
        if (expectedSql.Length == 0) throw new ArgumentException("ExpectedSql cannot be empty.", nameof(expectedSql));
        
        ExpectedParameters = expectedParameters ?? [];
        Id = id;
    }

    /// <summary>
    /// Initializes a new test case that expects an exception to be thrown.
    /// </summary>
    public SqlTestCase(Type expectedExceptionType, string? expectedExceptionMessage = null, string? id = null)
    {
        ExpectedExceptionType = expectedExceptionType ?? throw new ArgumentNullException(nameof(expectedExceptionType));
        ExpectedExceptionMessage = expectedExceptionMessage;
        Id = id;
    }

    /// <summary>
    /// Executes the SQL generation logic, captures the output state, and automatically 
    /// runs the query against a live database if an E2E connection is active.
    /// </summary>
    public void Act(Func<SqlQueryResult> act)
    {
        try
        {
            var result = act();
            ActualSql.Add(result.Sql);
            ActualParametersList.Add(result.Parameters.Select(p => p.Value).ToArray());

            // E2E Database Execution Bridge
            if (CurrentConnection.Value is { } connection)
            {
                using var command = connection.CreateCommand();
                command.CommandText = result.Sql;

                // Use raw ADO.NET mapping to avoid forcing a Dapper dependency on the testing library
                foreach (var p in result.Parameters)
                {
                    var param = command.CreateParameter();
                    param.ParameterName = p.Key;
                    param.Value = p.Value ?? DBNull.Value;
                    
                    // If your parameter model exposes DbType, uncomment the next line:
                    // param.DbType = p.DbType; 
                    
                    command.Parameters.Add(param);
                }

                // If this fails, the DB syntax error is naturally caught and added to ActualExceptions,
                // causing your SqlTestCaseAssert step to accurately fail the test.
                command.ExecuteNonQuery();
            }
        }
        catch (Exception ex)
        {
            ActualExceptions.Add(ex);
        }
    }

    public void Serialize(IXunitSerializationInfo info)
    {
        info.AddValue(nameof(ExpectedSql), ExpectedSql);
        info.AddValue(nameof(ExpectedExceptionType), ExpectedExceptionType?.AssemblyQualifiedName);
        info.AddValue(nameof(ExpectedExceptionMessage), ExpectedExceptionMessage);
        info.AddValue(nameof(ExpectedParameters), ExpectedParameters);
        info.AddValue(nameof(Id), Id);
    }

    public void Deserialize(IXunitSerializationInfo info)
    {
        ExpectedSql = info.GetValue<string[]>(nameof(ExpectedSql));
        ExpectedParameters = info.GetValue<object?[]>(nameof(ExpectedParameters)) ?? [];

        var expectedExceptionTypeName = info.GetValue<string>(nameof(ExpectedExceptionType));
        if (!string.IsNullOrEmpty(expectedExceptionTypeName))
        {
            ExpectedExceptionType = Type.GetType(expectedExceptionTypeName);
        }

        ExpectedExceptionMessage = info.GetValue<string>(nameof(ExpectedExceptionMessage));
        Id = info.GetValue<string>(nameof(Id));
    }

    public override string ToString()
    {
        return string.IsNullOrWhiteSpace(Id) ? "TestCase" : Id;
    }
}